### ISSUE TITLE
Parsing error in the Swift Package Index

### ISSUE THREAD

**Issue by finestructure** [yshrkt/NFCSupport#1]
Hello @yshrkt !

I just wanted to alert you to a parsing issue with your `Package.swift` fine in your default branch in the [Swift Package Index](https://swiftpackageindex.com). Your package is currently showing a 404 there because of it.

The issue is that your `Package.swift` file is inconsistent:

```
// swift-tools-version:4.2
…
    swiftLanguageVersions: [.v5_2]
}
```

This leads to:

```
❯ swift package dump-package
/Users/sas/Downloads/NFCSupport: error: manifest parse error(s):
/Users/sas/Downloads/NFCSupport/Package.swift:23:30: error: type 'SwiftVersion' has no member 'v5_2'; did you mean 'v4_2'?
    swiftLanguageVersions: [.v5_2]
                             ^~~~
                             v4_2
PackageDescription.SwiftVersion:4:10: note: 'v4_2' declared here
    case v4_2
         ^
Fatal error: Index out of range
fish: 'swift package dump-package' terminated by signal SIGILL (Illegal instruction)
```

Simply changing `v5_2` to `v4_2` on your default branch should fix it. We re-scan packages automatically and your package should com back online by itself then :)

**Comment by daveverwer** [comment]
It's probably `v5` that's needed rather than`v4_2` as I see you support Swift 5.2, there just is no value for `v5_2`. [Documentation here](https://developer.apple.com/documentation/swift_packages/swiftversion).

**Comment by yshrkt** [comment]
Hi @finestructure @daveverwer 
Thank you for your feedback.
I fixed it just now.

**Comment by finestructure** [comment]
Great, thank you! It's back online now :)  https://swiftpackageindex.com/yshrkt/NFCSupport
